version: '2.0'

services:
  healthcheck:
    container_name: healthcheck
    hostname: healthcheck
    build:
      context: ./
      args:
        http_port: 80
        ftp_port: 21
        root_path: "/wwwroot"
        extra_packages: ""
    restart: always
    #    ports:
    #      - "80:80"    # http
    #      - "21:21"    # ftp
    volumes:
      - "./mainline/:/wwwroot/healthcheck/mainline/"
      - "./images/:/wwwroot/healthcheck/images/"
      - "./next/:/wwwroot/healthcheck/next/"
      - "./stable/:/wwwroot/healthcheck/stable/"

